"""empty message

Revision ID: f994902f10bd
Revises: 
Create Date: 2024-11-15 18:05:44.967156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f994902f10bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookinfo',
    sa.Column('book_id', sa.String(length=10), nullable=False),
    sa.Column('book_name', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=20), nullable=True),
    sa.Column('publisher_time', sa.Date(), nullable=True),
    sa.Column('isbn', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('should_return_date', sa.DateTime(), nullable=True),
    sa.Column('borrow_status', sa.CHAR(length=3), nullable=True),
    sa.Column('ebook', sa.Text(), nullable=True),
    sa.Column('search_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('userinfo',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('user_type', sa.CHAR(length=7), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('prefer_type', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('borrow_book_num', sa.Integer(), nullable=True),
    sa.Column('search_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('borrow_record',
    sa.Column('record_id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=True),
    sa.Column('book_id', sa.String(length=10), nullable=True),
    sa.Column('borrow_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['bookinfo.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('return_record',
    sa.Column('record_id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=True),
    sa.Column('book_id', sa.String(length=10), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['bookinfo.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_record')
    op.drop_table('borrow_record')
    op.drop_table('userinfo')
    op.drop_table('bookinfo')
    # ### end Alembic commands ###
